export { AssetsView } from './assets'
export { AutomationView } from './automation'
export { MimView } from './mim'
export { ApprovalPanel, RegistrationWizard } from './register'
export { WechatPanel } from './wechat'
